name: CI

on:
  push:
    tags:    
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # HTML
    - uses: us4useu/sphinx-action@master
      with:
        docs-folder: "docs/"
    # PDF.
    - uses: us4useu/sphinx-action@master
      with:
        pre-build-command: "apt-get --allow-releaseinfo-change update -y  && apt-get install -y texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended latexmk"
        build-command: "make latexpdf"
        docs-folder: "docs/"
    - uses: softprops/action-gh-release@v1
      with:
        files: docs/_build/latex/user_manual.pdf
    # Publish docs on GH Pages.
    - name: Commit documentation changes
      run: |
        git clone https://github.com/us4useu/us4r_user_manual.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Updated GH pages." -a || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # ===============================
